#=============================================#
#                 v.1.2.8                     #  
#                 FLASH-MD 
#     𝗠𝗨𝗟𝗧𝗜𝗗𝗘𝗩𝗜𝗖𝗘 𝗪𝗛𝗔𝗧𝗦𝗔𝗣𝗣 𝗨𝗦𝗘𝗥 𝗕𝗢𝗧        #
#=============================================#
# 
#    * @project_name : Flash-Md 
#    * @author : France King 
#    * @instagram : https://www.instagram.com/@france.king1 
#    * @description : Flash-Md ,A Multi-functional whatsapp bot md.
#    * @version 1.2.8
# 
# Don't change this [ /franceking1/ ] name!
# Change from below link, else bot not works!

 

FROM quay.io/franceking1/flash-v2
RUN git clone https://github.com/franceking1/Flash-Md /root/Flash
WORKDIR /root/Flash/
RUN npm install
EXPOSE 8000
CMD ["npm","start" ] 
